# Generated by Django 3.2.9 on 2021-12-08 07:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0002_auto_20211208_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examdetails',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('is_attempted', models.BooleanField(default=False)),
                ('obtained_marks', models.IntegerField()),
                ('result', models.CharField(max_length=20)),
                ('exam_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam+examdetails+', to='teacher.exam')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student+hostdetials+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
