# Generated by Django 3.2.9 on 2021-12-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20211208_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetails',
            name='date',
            field=models.DateField(default='2001-10-10'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='examdetails',
            name='name',
            field=models.CharField(default='--', max_length=50),
        ),
    ]
