# Generated by Django 3.2.9 on 2021-12-16 03:12

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teacher', '0004_auto_20211215_1252'),
        ('student', '0007_alter_examdetails_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examdetails',
            name='date',
            field=models.DateField(default=datetime.date(2021, 12, 16)),
        ),
        migrations.AlterField(
            model_name='examdetails',
            name='exam_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examdetailsexamid', to='teacher.exam'),
        ),
        migrations.AlterField(
            model_name='examdetails',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attemptedby', to=settings.AUTH_USER_MODEL),
        ),
    ]
