# Generated by Django 3.2.9 on 2021-12-16 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20211216_0842'),
    ]

    operations = [
        migrations.AddField(
            model_name='examdetails',
            name='user_name',
            field=models.CharField(default='Na', max_length=20),
        ),
    ]
