# Generated by Django 3.2.9 on 2021-12-08 05:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('subname', models.CharField(default='Maths', max_length=70)),
                ('year', models.CharField(default='FE', max_length=5)),
                ('stream', models.CharField(default='None', max_length=30)),
                ('date', models.DateField()),
                ('starttime', models.TimeField()),
                ('endtime', models.TimeField()),
                ('hoster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user+exam+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('prim_key', models.AutoField(primary_key=True, serialize=False)),
                ('ques', models.TextField()),
                ('opt1', models.TextField()),
                ('opt2', models.TextField()),
                ('opt3', models.TextField()),
                ('opt4', models.TextField()),
                ('totaltime', models.DurationField()),
                ('correctoption', models.IntegerField()),
                ('marks', models.IntegerField()),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam+questions+', to='teacher.exam')),
            ],
        ),
    ]
