# Generated by Django 3.2.9 on 2021-12-08 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='examtotaltime',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='exam',
            name='totalmarks',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questions',
            name='totaltime',
            field=models.IntegerField(),
        ),
    ]
