# Generated by Django 3.2.9 on 2021-12-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_auto_20211208_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionsview', to='teacher.exam'),
        ),
    ]
