# Generated by Django 3.2.9 on 2021-12-15 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_questions_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='marks',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='questions',
            name='totaltime',
            field=models.IntegerField(default=1),
        ),
    ]
