# Generated by Django 3.2.9 on 2021-12-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20211215_1252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='examtotaltime',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='exam',
            name='totalmarks',
            field=models.IntegerField(default=10),
        ),
    ]
